// <auto-generated />
namespace computer_reparatieshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class usernameSwitch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usernameSwitch));
        
        string IMigrationMetadata.Id
        {
            get { return "202007141248443_usernameSwitch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
